CREATE TABLE IF NOT EXISTS users (
	id UUID NOT NULL PRIMARY KEY,
	email TEXT NOT NULL UNIQUE,
	username TEXT NOT NULL UNIQUE,
	hashed_password BYTEA NOT NULL,
	salt BYTEA NOT NULL,
	active BOOLEAN DEFAULT FALSE NOT NULL,
	admin BOOLEAN DEFAULT FALSE NOT NULL
);
