// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"time"

	"github.com/google/uuid"
)

type SigningKey struct {
	Name      string    `json:"name"`
	Value     []byte    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	HashedPassword []byte    `json:"hashed_password"`
	Salt           []byte    `json:"salt"`
	Active         bool      `json:"active"`
	Admin          bool      `json:"admin"`
}

type VerificationToken struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}
