// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signing_key.sql

package repository

import (
	"context"
)

const getOrCreateSigningKey = `-- name: GetOrCreateSigningKey :one
INSERT INTO signing_keys(name, value) VALUES($1, $2)
ON CONFLICT (name) DO UPDATE SET value = signing_keys.value
RETURNING name, value, created_at
`

type GetOrCreateSigningKeyParams struct {
	Name  string `json:"name"`
	Value []byte `json:"value"`
}

func (q *Queries) GetOrCreateSigningKey(ctx context.Context, arg GetOrCreateSigningKeyParams) (SigningKey, error) {
	row := q.db.QueryRow(ctx, getOrCreateSigningKey, arg.Name, arg.Value)
	var i SigningKey
	err := row.Scan(&i.Name, &i.Value, &i.CreatedAt)
	return i, err
}
