// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_token.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVerificationToken = `-- name: CreateVerificationToken :exec
INSERT INTO verification_tokens(token_hash, user_id, expires_at) VALUES($1, $2, $3)
`

type CreateVerificationTokenParams struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createVerificationToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteVerificationToken = `-- name: DeleteVerificationToken :exec
DELETE FROM verification_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteVerificationToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteVerificationToken, tokenHash)
	return err
}

const deleteVerificationTokensForUser = `-- name: DeleteVerificationTokensForUser :exec
DELETE FROM verification_tokens WHERE user_id = $1
`

func (q *Queries) DeleteVerificationTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerificationTokensForUser, userID)
	return err
}

const getVerificationToken = `-- name: GetVerificationToken :one
SELECT token_hash, user_id, expires_at, created_at FROM verification_tokens WHERE token_hash = $1
`

func (q *Queries) GetVerificationToken(ctx context.Context, tokenHash []byte) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationToken, tokenHash)
	var i VerificationToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
